name: Build and Push Docker Images

on:
  push:
    branches: [main, develop]
    paths: ["MicroserviceVersion/services/**"]
  pull_request:
    branches: [main]
    paths: ["MicroserviceVersion/services/**"]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: estevanb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Music Service
        uses: docker/build-push-action@v5
        with:
          context: ./MicroserviceVersion
          file: ./MicroserviceVersion/services/musics/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/musics-service:latest
            ${{ env.DOCKERHUB_USERNAME }}/musics-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Users Service
        if: hashFiles('MicroserviceVersion/services/users/Dockerfile') != ''
        uses: docker/build-push-action@v5
        with:
          context: ./MicroserviceVersion
          file: ./MicroserviceVersion/services/users/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/users-service:latest
            ${{ env.DOCKERHUB_USERNAME }}/users-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Chat Service
        if: hashFiles('MicroserviceVersion/services/chat/Dockerfile') != ''
        uses: docker/build-push-action@v5
        with:
          context: ./MicroserviceVersion
          file: ./MicroserviceVersion/services/chat/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/chat-service:latest
            ${{ env.DOCKERHUB_USERNAME }}/chat-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "✅ Docker images built and pushed successfully!"
          echo "🐳 Available images:"
          echo "   - ${{ env.DOCKERHUB_USERNAME }}/musics-service:${{ github.run_number }}"
          echo "   - ${{ env.DOCKERHUB_USERNAME }}/musics-service:latest"
