name: Build and Push Docker Images

on:
  push:
    branches: [main, develop]
    paths:
      - "MicroserviceVersion/services/**"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths: ["MicroserviceVersion/services/**"]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: estevanb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List files
        run: |
          echo "=== Verificando estructura de archivos ==="
          ls -la
          echo "=== Contenido de MicroserviceVersion ==="
          ls -la MicroserviceVersion/ || echo "MicroserviceVersion no existe"
          echo "=== Contenido de services ==="
          ls -la MicroserviceVersion/services/ || echo "services no existe"
          echo "=== Verificando Dockerfiles específicos ==="
          ls -la MicroserviceVersion/services/*/Dockerfile || echo "No se encontraron Dockerfiles"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if Music Service Dockerfile exists
        id: check-music
        run: |
          if [ -f "MicroserviceVersion/services/musics/Dockerfile" ]; then
            echo "music_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Music Service Dockerfile encontrado"
          else
            echo "music_exists=false" >> $GITHUB_OUTPUT
            echo "❌ Music Service Dockerfile NO encontrado"
          fi

      - name: Check if Users Service Dockerfile exists
        id: check-users
        run: |
          if [ -f "MicroserviceVersion/services/users/Dockerfile" ]; then
            echo "users_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Users Service Dockerfile encontrado"
          else
            echo "users_exists=false" >> $GITHUB_OUTPUT
            echo "❌ Users Service Dockerfile NO encontrado"
          fi

      - name: Check if Chat Service Dockerfile exists
        id: check-chat
        run: |
          if [ -f "MicroserviceVersion/services/chat/Dockerfile" ]; then
            echo "chat_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Chat Service Dockerfile encontrado"
          else
            echo "chat_exists=false" >> $GITHUB_OUTPUT
            echo "❌ Chat Service Dockerfile NO encontrado"
          fi

      - name: Build and push Music Service
        if: steps.check-music.outputs.music_exists == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./MicroserviceVersion
          file: ./MicroserviceVersion/services/musics/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/musics-service:latest
            ${{ env.DOCKERHUB_USERNAME }}/musics-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Users Service
        if: steps.check-users.outputs.users_exists == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./MicroserviceVersion
          file: ./MicroserviceVersion/services/users/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/users-service:latest
            ${{ env.DOCKERHUB_USERNAME }}/users-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Chat Service
        if: steps.check-chat.outputs.chat_exists == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./MicroserviceVersion
          file: ./MicroserviceVersion/services/chat/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/chat-service:latest
            ${{ env.DOCKERHUB_USERNAME }}/chat-service:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "✅ Docker images build process completed!"
          echo "🐳 Images attempted to build:"
          if [ "${{ steps.check-music.outputs.music_exists }}" == "true" ]; then
            echo "   ✅ ${{ env.DOCKERHUB_USERNAME }}/musics-service:${{ github.run_number }}"
          fi
          if [ "${{ steps.check-users.outputs.users_exists }}" == "true" ]; then
            echo "   ✅ ${{ env.DOCKERHUB_USERNAME }}/users-service:${{ github.run_number }}"
          fi
          if [ "${{ steps.check-chat.outputs.chat_exists }}" == "true" ]; then
            echo "   ✅ ${{ env.DOCKERHUB_USERNAME }}/chat-service:${{ github.run_number }}"
          fi
